[package]
name = "trunk-repro"
version = "0.1.0"
edition = "2021"
description = "Reproducing trunk feature selection bug"

[dependencies]
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = ["console"] }

[features]
feat = []
